services:
    pr-service:
      build: .
      
      container_name: pr-service

      ports:
      - '8080:8080'

      volumes:
        - pr-service-data-volume:/project/data/

volumes:
  pr-service-data-volume:
    name: pr-service-data